# Generated by Django 3.2 on 2021-04-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stmt_text', models.CharField(max_length=250)),
                ('stmt_status', models.IntegerField(default=0)),
                ('stmt_date', models.DateField()),
            ],
        ),
    ]
