# Generated by Django 3.2 on 2021-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stmt_stmt_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmt',
            name='stmt_status',
            field=models.CharField(max_length=5),
        ),
    ]
